# Generated by Django 5.1.3 on 2025-04-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='discount',
        ),
    ]
