# Generated by Django 5.1.3 on 2025-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
