# Generated by Django 5.1.3 on 2025-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='998f551a-121c-4c15-8868-366fd4bc5ab8', max_length=250),
        ),
    ]
