# Generated by Django 5.1.3 on 2025-02-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='00fc4ee9-bfca-4d34-b4e7-7fd17ae6c181', max_length=250),
        ),
    ]
