# Generated by Django 5.1.3 on 2024-12-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_last_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='last_at',
        ),
    ]
