# Generated by Django 5.1.3 on 2025-03-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='256c8734-3ebd-467e-b7c4-8d96a2a22f01', max_length=250),
        ),
    ]
