# Generated by Django 5.1.3 on 2025-03-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='2f3dddd7-347c-476b-8087-1902a2e87bf4', max_length=250),
        ),
    ]
