# Generated by Django 5.1.3 on 2025-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='940b764e-45e4-4906-9888-dfaa018637c6', max_length=250),
        ),
    ]
