# Generated by Django 5.1.3 on 2025-03-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='ee47b5f3-66c9-4b52-b43a-d9d9c3e0b0d4', max_length=250),
        ),
    ]
