# Generated by Django 5.1.3 on 2025-03-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='025f2a52-dbe0-4770-bd62-716aa82ae6c2', max_length=250),
        ),
    ]
