# Generated by Django 5.1.3 on 2025-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='d1b47a33-7169-4cb9-bec0-298829e544ee', max_length=250),
        ),
    ]
