# Generated by Django 5.1.3 on 2025-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='146701c6-7bfd-4aed-a3b6-05e628245b64', max_length=250),
        ),
    ]
