# Generated by Django 5.1.3 on 2025-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='30ec32aa-29a3-4f1e-9d2f-205bf14a1646', max_length=250),
        ),
    ]
