# Generated by Django 5.1.3 on 2024-12-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='348be926-7040-4edd-8379-8d69a33bb42d', max_length=250),
        ),
    ]
