# Generated by Django 5.1.3 on 2024-12-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='4f37ecf9-a19e-430a-a529-8eaba5699c54', max_length=250),
        ),
    ]
