# Generated by Django 5.1.3 on 2025-04-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='dfd52acf-f806-4fdd-9b6e-7b5fb7c15b4b', max_length=250),
        ),
    ]
