# Generated by Django 5.1.3 on 2024-12-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='22ff842a-37a1-4748-965e-a5572f36422a', max_length=250),
        ),
    ]
