# Generated by Django 5.1.3 on 2025-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='4f6ee9b5-b312-4787-b669-3013dc5979fd', max_length=250),
        ),
    ]
