# Generated by Django 5.1.3 on 2024-12-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='a7a8259b-5156-4217-8f27-4cfe160194f8', max_length=250),
        ),
    ]
