# Generated by Django 5.1.3 on 2025-01-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='5c34808f-5a61-48f8-aaef-d3cfeb5e4629', max_length=250),
        ),
    ]
