# Generated by Django 5.1.3 on 2025-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='563c5a5e-f2a9-4850-b07e-135b7f04de36', max_length=250),
        ),
    ]
