# Generated by Django 5.1.3 on 2025-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='c8962cbf-c449-4aef-ad7c-70b235a05c2a', max_length=250),
        ),
    ]
