# Generated by Django 5.1.3 on 2025-01-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='7b1fe8a2-cd07-4652-987f-a1453215d8dc', max_length=250),
        ),
    ]
