# Generated by Django 5.1.3 on 2025-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='4192efb9-8f67-447e-881d-801896879574', max_length=250),
        ),
    ]
