# Generated by Django 5.1.3 on 2025-01-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='e0a4e492-e73e-452f-bf25-fe8c4894ef46', max_length=250),
        ),
    ]
