# Generated by Django 5.1.3 on 2025-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_cart_coupon_cart_coupon_applied_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='e737705c-1f9f-4955-a3f7-49e5957cfb8f', max_length=250),
        ),
    ]
