# Generated by Django 5.1.3 on 2025-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='65caef5e-4b6a-47d2-8a90-58bc0aa64e5e', max_length=250),
        ),
    ]
