# Generated by Django 5.1.3 on 2025-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='443b1988-a52a-4206-8440-3210af2850d1', max_length=250),
        ),
    ]
