# Generated by Django 5.1.3 on 2025-04-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_cart_coupon_processed_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='b0659b71-8649-4437-98ec-5031afd7e5eb', max_length=250),
        ),
    ]
