# Generated by Django 5.1.3 on 2025-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='0c80c146-3454-4881-ba2a-cb880b410ad2', max_length=250),
        ),
    ]
