# Generated by Django 5.1.3 on 2025-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_processed',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='15347d6e-1e64-4909-8130-b218cc5bd740', max_length=250),
        ),
    ]
