# Generated by Django 5.1.3 on 2025-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='aa22fb14-f56f-4996-a07d-5a0caf30fbbf', max_length=250),
        ),
    ]
