# Generated by Django 5.1.3 on 2025-04-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_remove_cart_coupon_processed_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon_applied',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='2132007d-f143-4e9c-8cf3-1555c21db34b', max_length=250),
        ),
    ]
