# Generated by Django 5.1.3 on 2025-04-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_remove_cart_coupon_remove_cart_coupon_applied_and_more'),
        ('promotions', '0002_delete_promotion_coupon_usage_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='61e7c73a-4d20-49f3-a94d-6f671022e0e9', max_length=250),
        ),
    ]
