# Generated by Django 5.1.3 on 2025-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='c8310686-e6ce-4611-999e-9986e5ec4cd3', max_length=250),
        ),
    ]
