# Generated by Django 5.1.3 on 2025-04-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_cartitem_coupon_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='88270e33-3b25-4730-b955-d11113327d68', max_length=250),
        ),
    ]
