# Generated by Django 5.1.3 on 2025-01-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='069d7a58-61c6-4f1d-8258-f8c911404b47', max_length=250),
        ),
    ]
