# Generated by Django 5.1.3 on 2025-01-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='b59fcbb7-5e94-4934-a528-2dad5bf90692', max_length=250),
        ),
    ]
