# Generated by Django 5.1.3 on 2025-04-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_cartitem_coupon_processed_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='b993f2e6-f797-461c-b93f-da2ea18a77a4', max_length=250),
        ),
    ]
