# Generated by Django 5.1.3 on 2025-01-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='14ccb180-919d-47cc-8855-70bd94d5591a', max_length=250),
        ),
    ]
