# Generated by Django 5.1.3 on 2025-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_remove_cartitem_coupon_processed_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='6aa9cef3-f92c-4efd-82e9-4d91a88c54d6', max_length=250),
        ),
    ]
