# Generated by Django 5.1.3 on 2025-01-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='8235e5ff-0b15-4126-b0dd-b68d230cbd9e', max_length=250),
        ),
    ]
