# Generated by Django 5.1.3 on 2025-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='1f683623-a07f-43ef-a209-7f7fc4839274', max_length=250),
        ),
    ]
