# Generated by Django 5.1.3 on 2025-01-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='024ab05e-56e4-4ce8-a5bc-09790e8026e6', max_length=250),
        ),
    ]
