# Generated by Django 5.1.3 on 2025-04-14 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_remove_cartitem_coupon_alter_cart_cart_id'),
        ('promotions', '0002_delete_promotion_coupon_usage_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='eeab7bc5-7536-41f9-9c27-3480b54b8a74', max_length=250),
        ),
    ]
