# Generated by Django 5.1.3 on 2025-01-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='61419d2f-a306-4e34-a616-ee8cd05fe699', max_length=250),
        ),
    ]
