# Generated by Django 5.1.3 on 2025-04-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_cart_coupon_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='96cec57e-afbc-4d4c-915d-7eeb1c5596ea', max_length=250),
        ),
    ]
