# Generated by Django 5.1.3 on 2025-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='a8a5facc-d9e5-4bd0-9e8c-5a89db3685e1', max_length=250),
        ),
    ]
