# Generated by Django 5.1.3 on 2025-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='fda47301-7ba2-4ec0-9ef6-ee64f5ffe153', max_length=250),
        ),
    ]
