# Generated by Django 5.1.3 on 2025-01-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='084c3d0d-d2ac-4ea5-96a9-01531318299a', max_length=250),
        ),
    ]
