# Generated by Django 5.1.3 on 2025-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='4a860158-334d-4b67-a71b-7c73b563918a', max_length=250),
        ),
    ]
