# Generated by Django 5.1.3 on 2025-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_cart_is_guest_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='cf03a50c-cbd8-4cbd-b543-2d2919d2e01c', max_length=250),
        ),
    ]
