# Generated by Django 5.1.3 on 2025-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_promotion_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='04a1e7dd-25e3-42a9-9197-ffba38f3a82c', max_length=250),
        ),
    ]
