# Generated by Django 5.1.3 on 2025-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='17d5e02d-9369-4a18-b3eb-47d9582894c6', max_length=250),
        ),
    ]
