# Generated by Django 5.1.3 on 2025-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='0b74b1cd-2f02-4d03-8078-d01cbfeffe60', max_length=250),
        ),
    ]
