# Generated by Django 5.1.3 on 2025-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='57ae04fc-3f60-40cc-beea-7b0d8715c695', max_length=250),
        ),
    ]
