# Generated by Django 5.1.3 on 2025-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='d8256ddf-ab84-4eed-8905-c8a115f62170', max_length=250),
        ),
    ]
