# Generated by Django 5.1.3 on 2025-01-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='8cc3c61e-2c04-4712-b453-0ff1c6624590', max_length=250),
        ),
    ]
