# Exported from Render on 2025-02-06T12:41:35Z
services:
- type: web
  name: Django-belle-e-commerce-project-1
  runtime: node
  repo: https://github.com/Habib40/Django-belle-e-commerce-project
  plan: free
  envVars:
  - key: DEBUG
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_PORT
    sync: false
  - key: DATABASE_HOST
    sync: false
  - key: DATABASE_PASSWORD
    sync: false
  - key: DATABASE_USER
    sync: false
  - key: DATABASE_NAME
    sync: false
  - key: IT_PAY_BD_API_KEY
    sync: false
  - key: STRIPE_SECRET_KEY
    sync: false
  - key: STRIPE_PUBLISHABLE_KEY
    sync: false
  - key: STEADFAST_BASE_URL
    sync: false
  - key: STEADFAST_SECRET_KEY
    sync: false
  - key: STEADFAST_API_KEY
    sync: false
  region: oregon
  buildCommand: ecommerce.wsgi.application
  startCommand: ecommerce.wsgi.application
version: "1"
