version: 1
services:
  - type: web
    name: bele    # Change this to a name for your service
    env: python
    runtime:python3
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ecommerce.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DB_NAME
        value: Ecommerce   # Update with your database name
      - key: DB_USER
        value: admin    # Update with your database user
      - key: DB_PASSWORD
        value: admin # Update with your database password
      - key: DB_HOST
        value: localhost     # Update with your database host
      - key: DB_PORT
        value: 5432     # Update with your database port
      - key: SECRET_KEY
        value: django-insecure-rqszx%yl*+!m!5(o@(g!2keuyhu5)oncur@qqlla*dg6c&g3sk       # Update with your Django secret key
      - key: DEBUG
        value: 'false'          # Change to 'true' for debugging if needed
