# Generated by Django 5.1.3 on 2025-03-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_sale_in_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_sale_time',
        ),
        migrations.AddField(
            model_name='product',
            name='last_sold_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
