# Generated by Django 5.1.3 on 2024-12-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
