# Generated by Django 5.1.3 on 2025-04-04 03:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_last_sale_in_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moreInformation',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
