# Generated by Django 5.1.3 on 2025-04-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_moreinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='moreInformation',
            new_name='more_Information',
        ),
    ]
