# Generated by Django 5.1.3 on 2024-12-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productcolor_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Product Color', 'verbose_name_plural': 'Product Colors And Sizes'},
        ),
    ]
